config/routes.rb
Rails.application.routes.draw do
  resources :details
  resources :people
  resources :tasks
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
end

app/models/detail.rb
class Detail
  include Mongoid::Document
  field :title, type: String
  field :work_hours, type: Integer
  field :description, type: String

  belongs_to :task
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: [:show, :edit, :update, :destroy]

  # GET /details
  # GET /details.json
  def index
    @details = Detail.all
  end

  # GET /details/1
  # GET /details/1.json
  def show
  end

  # GET /details/new
  def new
    @detail = Detail.new
  end

  # GET /details/1/edit
  def edit
  end

  # POST /details
  # POST /details.json
  def create
    @detail = Detail.new(detail_params)

    respond_to do |format|
      if @detail.save
        format.html { redirect_to @detail, notice: 'Detail was successfully created.' }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1
  # PATCH/PUT /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to @detail, notice: 'Detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail.destroy
    respond_to do |format|
      format.html { redirect_to details_url, notice: 'Detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detail_params
      params.require(:detail).permit(:title, :work_hours, :description)
    end
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_form.html.erb
<%= form_for(detail) do |f| %>
  <% if detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
      <% detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :work_hours %>
    <%= f.number_field :work_hours %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/details/edit.html.erb
<h1>Editing Detail</h1>

<%= render 'form', detail: @detail %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

app/views/details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Details</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Work hours</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @details.each do |detail| %>
      <tr>
        <td><%= detail.title %></td>
        <td><%= detail.work_hours %></td>
        <td><%= detail.description %></td>
        <td><%= link_to 'Show', detail %></td>
        <td><%= link_to 'Edit', edit_detail_path(detail) %></td>
        <td><%= link_to 'Destroy', detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detail', new_detail_path %>

app/views/details/new.html.erb
<h1>New Detail</h1>

<%= render 'form', detail: @detail %>

<%= link_to 'Back', details_path %>

app/views/details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @detail.title %>
</p>

<p>
  <strong>Work hours:</strong>
  <%= @detail.work_hours %>
</p>

<p>
  <strong>Description:</strong>
  <%= @detail.description %>
</p>

<%= link_to 'Edit', edit_detail_path(@detail) %> |
<%= link_to 'Back', details_path %>